server:
  port: 8080

spring:
  application:
    name: customer
  rabbitmq:
    addresses: localhost:5172

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true