spring:
  application:
    name: product
  cloud:
    inetutils:
      timeout-seconds: 10
      ignored-interfaces:
        - Software*
        - VMware*
        - Hyper*


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true


server:
  port: 8081

cors:
  allowedOrigins:
    localhost:
      path: /api/v1/products
      instanceUrl: http://localhost:8080