spring:
  application:
    name: notification
  rabbitmq:
    addresses: localhost:5172

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

cors:
  allowedOrigins:
    localhost:
      path: /api/v1/notification
      instanceUrl: http://localhost:8080