spring:
  application:
    name: eureka-server
  cloud:
    inetutils:
      timeout-seconds: 10
      ignored-interfaces:
        - Software*
        - VMware*
        - Hyper*

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true